export const FETCH_FEATURED_MOVIE_REQUEST = 'FETCH_FEATURED_MOVIE_REQUEST';
export const FETCH_FEATURED_MOVIE_SUCCESS = 'FETCH_FEATURED_MOVIE_SUCCESS';
export const FETCH_FEATURED_MOVIE_FAILURE = 'FETCH_FEATURED_MOVIE_FAILURE';
